### ISSUE TITLE
Inserting Services, About and FAQ pages

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#11]
We need to create interactive & informative Services, About and FAQ pages on the front end for potential customers & funders. The pages already exist - what we need is good CSS design to go along with the content.

Tobi will input content + designs & Tunde will implement.

Will include some examples from similar websites of what the page structures may look like. (NB: the FAQ page already has a specific design - we just need to keep it functional).

- [ ] Tobi to create mock wireframes of what the pages should look like

- [ ] Tunde to implement wireframes

**Comment by tobiobisanya** [comment]
See the document below for the content of the Services & About Pages: 
https://docs.google.com/document/d/13y3QEGcIM7XANp3CqmcS7ruu5-0EPW1OpGOc_CoNxYM/edit?usp=sharing

Wireframes below. The styling that I'm going for with the x2 column set up of the page is inspired from Babylon Health - a competitor of ours: https://www.babylonhealth.com/how-it-works

Do let me know if you have any questions about what we're going for. 

I will upload all of the required images in the wireframes for you onto this page. 
![about](https://cloud.githubusercontent.com/assets/25155149/22942594/0626c6d6-f2e2-11e6-9280-4463a10c9415.JPG)
![services](https://cloud.githubusercontent.com/assets/25155149/22942595/06322cf6-f2e2-11e6-95ed-49535e6c6f55.jpg)

**Comment by tobiobisanya** [comment]
Front Page of the website needs slight amendment --> the text directly underneath "Health Advice from our Experts" should be deleted. just leave the articles as they are with no subheader. 

There also seems to be an issue with the animated services icons appearing after the section of the page they're on is scrolled by?

**Comment by TundeMichael** [comment]
Hi @tobiobisanya  the text has been deleted, next upload will reflect the change. I dont think i understand the last part of your message 

"There also seems to be an issue with the animated services icons appearing after the section of the page they're on is scrolled by?"

Please explain a bit further. Thanks

**Comment by tobiobisanya** [comment]
@TundeMichael - don't worry about the last part of the message! have just reviewed it  on mobile & desktop & it only seems to be an issue (very minor) on Desktop.

**Comment by tobiobisanya** [comment]
**Services**
** Icon1 **: 
![assistant- -facebook](https://cloud.githubusercontent.com/assets/25155149/23586442/b5fa37f6-018c-11e7-969b-00b2632b5f6b.jpg)

**Icon 2** 
![global-professionals](https://cloud.githubusercontent.com/assets/25155149/23586540/2066eb5a-018f-11e7-8029-c7096404a0b5.jpg)

**Icon 3** 
![family-record](https://cloud.githubusercontent.com/assets/25155149/23765352/dcbc7736-04f8-11e7-91f3-a27ced1ec794.png)

**Comment by tobiobisanya** [comment]
**About Section**

About_img_1: (you may need to amend the size of this image to optimise for mobile) - let me know if you need me to help with that.
![shutterstock_243770785](https://cloud.githubusercontent.com/assets/25155149/23765561/82687568-04f9-11e7-8521-90a0e0ecb777.jpg)

About_Img_2: 
![27715-200](https://cloud.githubusercontent.com/assets/25155149/23765878/a2c8dc0c-04fa-11e7-9146-2c778fcc4bbc.png)

About_Img_3: 
![hand-shake-with--phone-icon-92648](https://cloud.githubusercontent.com/assets/25155149/23765894/af1abebc-04fa-11e7-97c1-8489e90caba1.png)

@TundeMichael - presently leave the bottom section of this page clear. don't include the meet the team section. we'll sort that out at a later stage. 

Please include the "work with us" section from my wireframe.

Cheers.

**Comment by TundeMichael** [comment]
FAQ has been fixed earlier in the project. Please check out the Services and About. I think we need new images for the full-width ones we have there. You will notice i had to give them unnecessarily large height as they look distorted with anything less although they seem OK on mobile. If you think we can manage them for the main time, then you can just close this issue.

**Comment by tobiobisanya** [comment]
@TundeMichael we will manage this for now. cheers!
