### ISSUE TITLE
Changing the Patient users's back end menus

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#13]
Need to amend the header descriptions underneath the titles in each of the patient's back end menus - at the moment they are non specific and not helpful to the patient in explaining what they can do in each section of the app.

- [x] Tobi to Explain what each header must state
- [x] Implement changes
- [ ] Remove current Menu option "Search History" from the users view 
- [ ] Amend URLs for each page

**Comment by tobiobisanya** [comment]
Each header section in the back end has a subheading beneath the main title of the heading (for the user) - we need to amend what they say. 

The first one - Message - **header** = "**Ask a Numa Doctor**" **subheader** "Enter a message below & talk securely and confidentially with one of our Doctors. Please enter as much information as possible.


Saved Items - **header** = "**Personal Health Library**" the **subheader** should read: "Read through your favourite Numa health content" 

My Profile = **header** = "**Person's name's profile**" - **subheader** should read: "Your secure Personal Health Record"

Change Password = **header** - "**Change your password**" - no subheader. - also amend the description boxes so it is clear what the person needs to enter. is it the new password and then to confirm the new password - or is it current password - then new password? 

also, include standard password advice - "A strong password includes a mix of Numbers, Symbols, Capital Letters, and Lower-Case Letters."

**Comment by tobiobisanya** [comment]
In addition, could we remove the current Menu item entitled - "Search History" please.

**Comment by TundeMichael** [comment]
@tobiobisanya I will leave this change to till later in the project especially the URLs. They are more than just URLs, they are also tied to folders and other resources

**Comment by tobiobisanya** [comment]
@tundemichael - don't worry, leave the URLs - very unimportant.

**Comment by TundeMichael** [comment]
@tobiobisanya This has been resolved. Please login as a patient to check.

**Comment by tobiobisanya** [comment]
@TundeMichael - We just need to include the following text into the Menu + Header areas: 
Cheers.

Each header section in the back end has a subheading beneath the main title of the heading (for the user) - we need to amend what they say.

The first one - Message - header = "Ask a Numa Doctor" subheader "Enter a message below & talk securely and confidentially with one of our Doctors. Please enter as much information as possible.

Saved Items - header = "Personal Health Library" the subheader should read: "Read through your favourite Numa health content"

My Profile = header = "Person's name's profile" - subheader should read: "Your secure Personal Health Record"

also, include standard password advice - "A strong password includes a mix of Numbers, Symbols, Capital Letters, and Lower-Case Letters."
