### ISSUE TITLE
Create Parallax / Scroll effect to home page 

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#22]
http://www.thelightphone.com

use this for reference

we need to move the current picture that is behind the search box to be the first thing that users see when they open asknuma.com.

this image will also have some text overlayed on top of it all in lowercase - font: Aileron (I will send the font kit). 

then you will have a small arrow at the bottom the picture prompting you to scroll down. when you scroll down, you are met with the current home page - with the search box being overplayed on top of a plain background - colour to be confirmed.

**Comment by tobiobisanya** [comment]
This is the picture you will need @TundeMichael 

![shutterstock_439120777- small](https://cloud.githubusercontent.com/assets/25155149/23766370/72f98bdc-04fc-11e7-8d0c-659eb35aff88.jpg)

let me know if you need the size to be amended so it can load quicker.

**Comment by TundeMichael** [comment]
@tobiobisanya All the workaround i tried didn't quite look good. Like i said the other time on Skype, parallax is effect is actually not so complex to implement, the major problem is that the current landing page has address bar which doesn't make parallax possible naturally. 

If parallax is a must, i will suggest a redesign of the landing page.

**Comment by tobiobisanya** [comment]
@TundeMichael  - nah that's fine man. don't worry about it. cheers.
