### ISSUE TITLE
FAQ Page Redesign

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#24]
Make it more fit for purpose & easier to input information.

- [ ] To edit: 
Edit Categories to: 
- Getting started with Numa 
- Subscriptions
- Accounts and payments 
- Consultations
- Security and Privacy
- Troubleshooting

Other than that, I think it's good to go.

**Comment by TundeMichael** [comment]
@tobiobisanya this is customizable from the UI.  I will explain how in a mail soon.
