### ISSUE TITLE
Subscription Management Process

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#25]
Need to create processes for: 

1. Subscription confirmation email: 
Find the email content in this google document: 
https://docs.google.com/document/d/1mOtLeQgVArclC7Zi72NC2ZEXEy5dvkcPLprwTz12lbo/edit?usp=sharing

2. In their profile page - users will be shown what type of subscription package they are on and the renewal date of that subscription. 

3. In their Profile page - users will have a button to allow them to Cancel Subscription. 
This button will be located right at the top of the page next to the text showing them what subscription they are on. 

4. On choosing to cancel their subscription - users should be taken to a confirmation page - where they will be asked to confirm that they want to cancel their subscription. They should have a tick-box that asks them if they would like all of their data to be destroyed or if they’d like us to keep it, because they may be back - there should be an explanation that if they choose to cancel, they will be sent an email to confirm this and that they will lose access to all of the features of Numa Protect. 	
Once they select what they would like us to do with their data  Once they have confirmed they want to cancel their subscription and what they would like us to do with their personal data, they should be taken to a confirmation page saying we are sorry to see them go. 

_At this stage, this user should lose access to all of the back-end functionality of the Numa app._ 

**Conditionalities**: 
Users should not be able to access any part of the back-end without having selected a subscription package.

**Comment by TundeMichael** [comment]
@tobiobisanya This has been completed. Please login as a user to test. You can now delete your account (thou it doesn't complete remove you from the system at the moment, i will uncomment the total removal when we're ready to lunch), both completely and partially. Open tickets for any issue found or adjustments necessary.
