### ISSUE TITLE
Migrate Asknuma.com/v2 to asknuma.com

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#30]

**Comment by TundeMichael** [comment]
Hi @tobiobisanya i might charge for a day or 2 for this depending on how it goes. Migrations are usually problematic and alot of testing and fine tuning will definitely arise as some things will certainly break.

**Comment by TundeMichael** [comment]
@tobiobisanya Migration has been carried out and the old site decommissioned so the v2 link will no longer work. 
I'm still monitoring and configuring the error pages but if you notice any bug in the mean time, please open issues for them.

**Comment by tobiobisanya** [comment]
@TundeMichael  - brilliant cheers. seen the migration. if I see any big gaping errors will open an issue.
