### ISSUE TITLE
Minor UX issue

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#32]
The text in this box when users are selecting a health problem to read about after their initial search is out of sync with the rest of the font and design of the site. 

Could we amend the font to be similar to the rest of the site? 

See attached image for which font I mean. 

<img width="398" alt="screen shot 2017-03-22 at 12 45 44" src="https://cloud.githubusercontent.com/assets/25155149/24194213/e57305ca-0efd-11e7-8efc-d345d84fb6c5.png">

**Comment by TundeMichael** [comment]
Please check my new color choice and if you have another one in mind, just drop the color code or description for me

**Comment by tobiobisanya** [comment]
@TundeMichael - sorry man! I think you've misunderstood my comment. the font was the problem - i.e. Times New Roman/Arial/Calibri - not the colour of the text box. 

I think the font we have used in the rest of the app is **Aileron** 

I've attached the font kit here just in case you need it so the page can look unifrom. would you also be able to make the text in that box non-capitalised? 

[aileron.zip](https://github.com/numahealth/Asknuma/files/870629/aileron.zip)

**Comment by TundeMichael** [comment]
@tobiobisanya I think the current color now looks better (more uniform that what was there). Should i change it back or just work on the font now?

**Comment by tobiobisanya** [comment]
@TundeMichael bro - I think the colour is brilliant :) - just changing the font would be brilliant. cheers!

**Comment by TundeMichael** [comment]
@tobiobisanya The font has now been changed to 'Aileron' and the first letter of each word capitalized. Please have a look. You can just open the issue back if there is still need for amendment. Thanks
