### ISSUE TITLE
Review Sign-Up Process

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#33]
I have just tried to register for a new account & there are two apparent issues: 

1. Immediately after registering, there is no obvious thank you message to acknowledge that the user has succesfully registered for an account & we will be in touch (this existed before - so unsure why this has changed?) 

2. The welcome SMS message you receive via Twilio has no information in it anymore - it is just a 0. 
(FYI - I have checked the Twilio account & there are still $11 USD there so I'm doubtful that is the root of the bug.)

Kindly review theses issues @TundeMichael 

<img width="437" alt="screen shot 2017-03-22 at 13 16 16" src="https://cloud.githubusercontent.com/assets/25155149/24195367/19bf6608-0f02-11e7-9e43-5b260d00c323.png">

![img_7720](https://cloud.githubusercontent.com/assets/25155149/24195482/99bcf118-0f02-11e7-8a53-ccb8b2e91074.png)

**Comment by TundeMichael** [comment]
Fixed
