### ISSUE TITLE
Point of Failure at Registration 

### ISSUE THREAD

**Issue by TundeMichael** [numahealth/Asknuma#5]
The registration process calls 2 external services Twilio to send SMS and MailChimp to add the user to the mailing list. The 2 calls are made before the user’s details are even stored in the database at all and there is not error handling mechanism to handle the event of any of the external calls failing. The current behavior crashes the process and the user’s details will not be saved.
This needs to be redesigned.

 **Tasks**
- [ ] Amend current workflow not to send data to external services before data has been saved to our DB
- [ ]  Include forced process of ticking box to accept that one has read Terms of Service + read Privacy Policy

**Comment by tobiobisanya** [comment]
*Amend flow* - as per Tunde's suggestions. 

We also need to amend the process by getting users to tick a box stating that have read and agree to our terms of use AND provide them with a link to read the privacy policy **before** they can register. 

Terms of use and Privacy policy links are in the footer on the front page.
