### ISSUE TITLE
2b. Amending the number and content of emails sent to users

### ISSUE THREAD

**Issue by tobiobisanya** [numahealth/Asknuma#6]
Emails are sent to users after sign-up and during their use of the app.

- [x] Tobi to define the way emails are currently send the the way we want emails to be sent to users + when they are to be sent (lay out conditionality's). 
- [ ] Tunde to implement the emails + their content.

**Comment by tobiobisanya** [comment]
@TundeMichael the emails we'll need to send, & at which point they will need to be sent in the User's flow through the Asknuma app are in this document (I've invited you on Google): 

[https://docs.google.com/document/d/1mOtLeQgVArclC7Zi72NC2ZEXEy5dvkcPLprwTz12lbo/edit?usp=sharing](url)

**Comment by TundeMichael** [comment]
@tobiobisanya This has been completed. You can test by login in as a user and cancel your subscription. Please remember the final data deletion leg is intentionally held till we're about to launch.
